-- Data/TBC/VendorPrices.lua
-- AUTO-GENERATED by scripts/generate_recipes.py (--vendor-prices-only). Do not edit by hand.
-- Per-unit vendor BUY price (copper) for CONFIRMED vendor-stocked reagents only.
-- WHY a separate itemId-keyed table (not a field on each reagent): a reagent like Silken
-- Thread appears in hundreds of recipes; one keyed table avoids duplicating the price and
-- the drift that invites. WHY per-unit (not raw BuyPrice): BuyPrice is a per-
-- VendorStackCount BATCH price (vials sell in 5s); storing it raw 5x-overprices Alchemy.
-- WHY an allowlist (not BuyPrice>0): 73% of all items carry an intrinsic BuyPrice incl.
-- drops/herbs/ore; vendor-buyability is human-verified. See Data/Sources/vendor_reagents.json.
local ADDON_NAME, CraftLib = ...

CraftLib:RegisterVendorPrices({
    profile = "TBC",  -- runtime load-guard: registers only on the matching client profile
    prices = {
        [1179] = 25,  -- Ice Cold Milk (BuyPrice 125 / VendorStackCount 5)
        [2320] = 10,  -- Coarse Thread (BuyPrice 10 / VendorStackCount 1)
        [2321] = 100,  -- Fine Thread (BuyPrice 100 / VendorStackCount 1)
        [2325] = 1000,  -- Black Dye (BuyPrice 1000 / VendorStackCount 1)
        [2604] = 50,  -- Red Dye (BuyPrice 50 / VendorStackCount 1)
        [2605] = 100,  -- Green Dye (BuyPrice 100 / VendorStackCount 1)
        [2678] = 2,  -- Mild Spices (BuyPrice 10 / VendorStackCount 5)
        [2692] = 40,  -- Hot Spices (BuyPrice 40 / VendorStackCount 1)
        [2880] = 100,  -- Weak Flux (BuyPrice 100 / VendorStackCount 1)
        [3371] = 4,  -- Empty Vial (BuyPrice 20 / VendorStackCount 5)
        [3372] = 40,  -- Leaded Vial (BuyPrice 200 / VendorStackCount 5)
        [3466] = 2000,  -- Strong Flux (BuyPrice 2000 / VendorStackCount 1)
        [3713] = 160,  -- Soothing Spices (BuyPrice 160 / VendorStackCount 1)
        [3857] = 500,  -- Coal (BuyPrice 500 / VendorStackCount 1)
        [4289] = 50,  -- Salt (BuyPrice 50 / VendorStackCount 1)
        [4291] = 500,  -- Silken Thread (BuyPrice 500 / VendorStackCount 1)
        [4340] = 350,  -- Gray Dye (BuyPrice 350 / VendorStackCount 1)
        [4341] = 500,  -- Yellow Dye (BuyPrice 500 / VendorStackCount 1)
        [4342] = 2500,  -- Purple Dye (BuyPrice 2500 / VendorStackCount 1)
        [6260] = 50,  -- Blue Dye (BuyPrice 50 / VendorStackCount 1)
        [6261] = 1000,  -- Orange Dye (BuyPrice 1000 / VendorStackCount 1)
        [8343] = 2000,  -- Heavy Silken Thread (BuyPrice 2000 / VendorStackCount 1)
        [8925] = 500,  -- Crystal Vial (BuyPrice 2500 / VendorStackCount 5)
        [10290] = 2500,  -- Pink Dye (BuyPrice 2500 / VendorStackCount 1)
        [14341] = 5000,  -- Rune Thread (BuyPrice 5000 / VendorStackCount 1)
        [18256] = 4000,  -- Imbued Vial (BuyPrice 20000 / VendorStackCount 5)
        [18567] = 150000,  -- Elemental Flux (BuyPrice 150000 / VendorStackCount 1)
        [30817] = 5,  -- Simple Flour (BuyPrice 25 / VendorStackCount 5)
    },
})
